# https://argocd-applicationset.readthedocs.io/en/stable/
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-cluster-addons
spec:
  generators:
  - list:
      elements:
      - repoURL: https://github.com/jeevanions/app-collection.git      
        path: apps/application1
        revision: main
        name: application1
        namespace: application1
      - repoURL: https://github.com/jeevanions/app-collection.git
        path: apps/application2
        revision: main
        name: application2
        namespace: application2
      - repoURL: https://github.com/jeevanions/third-app.git
        path: apps/application3
        revision: main
        name: application3
        namespace: application3

  # - git:
  #     repoURL: https://github.com/jeevanions/app-collection.git
  #     revision: main
  #     directories:
  #     - path: apps/*
  # - git:
  #     repoURL: https://github.com/jeevanions/third-app.git
  #     revision: main
  #     directories:
  #     - path: apps/*
      
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: '{{repoURL}}'
        targetRevision: '{{revision}}'
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'